### ISSUE TITLE
Provide OpenBAS agent for x86_64 architecture

### ISSUE THREAD

**Issue by vSachanski** [OpenBAS-Platform/agent#12]
Using the install script for OpenBAS agent on x86_64 macOS doesn't work. The binary that's downloaded appears to be for the wrong architecture even though the script detects it correctly. I think the `openbas-agent-latest` binary hosted in the JFrog artifactory (https://filigran.jfrog.io/ui/native/openbas-agent/macos/x86_64/) is wrong as it appears to be for arm64. The previous version (openbas-agent-1.1.1) is correct:

```
file -b ~/Downloads/openbas-agent-latest
Mach-O 64-bit executable arm64

file -b ~/Downloads/openbas-agent-1.1.1
Mach-O 64-bit executable x86_64
```

OpenBAS version: 1.4.0

**Comment by richard-julien** [comment]
Hi @vSachanski, thanks for the report
MacOS x86 was removed from circleci builder recently.

We will work to bring back the support of mac os x86

**Comment by richard-julien** [comment]
Agent and implant for mac x86 is now available for latest version of openbas.
