### ISSUE TITLE
An error occur when we try to install an agent over an existing installation of the agent

### ISSUE THREAD

**Issue by Christian-DONGMO** [OpenBAS-Platform/agent#8]
If there is an installation of openBAS-agent on an asset, and then you try to re-install again, you get the following error
![img](https://github.com/OpenBAS-Platform/agent/assets/170315828/5c98f57b-ff00-4749-b907-65a9d7bedfb0)

**Comment by SamuelHassine** [comment]
@Christian-DONGMO I think if you are using the proper command line it will work, as we ensure to stop-service before re-installing.

**Comment by SamuelHassine** [comment]
Doing multiple times `iex (iwr "https://testing.obas.staging.filigran.io/api/agent/installer/openbas/windows/XXX").Content` is working properly.

**Comment by savacano28** [comment]
**Actions:**
Install Agent (using iwr ...): **OK**
Status Agent: **Running**
Uninstall Agent: **OK (cleaned files in folder, but openbas-agent.exe persists, and service is running)**
Status agent: **Still running**
Stop service: **manual**
Reinstall with command: **Error cannont stop service, cause was stopped before :)** 
Status Agent: **Running (endpoint on openbas ui ok)**

After uninstallation, **the service and executable file** remain active. Including a step to stop the service during the uninstallation process will delete all associated files.

The **Stop service** command is included in the installation process.

**Comment by savacano28** [comment]
No reproducible.

**Comment by RomuDeuxfois** [comment]
What is the status of this bug ?
Should it be closed @Christian-DONGMO ?

**Comment by savacano28** [comment]
@RomuDeuxfois Yes! We tested with Christian, and it was not repeatable.
